[package]
name = "rootfinding"
version = "0.0.1"
authors = ["Peter Jin <peterhaijin@gmail.com>"]

[lib]
name = "rootfinding"
path = "src/lib.rs"

[dev-dependencies]
dualnum = { path = "../libdualnum" }

[dependencies]
arithmetic = { path = "../libarithmetic" }
